src/CreaCom/ProjectBundle/Entity/Membre.php
<?php

namespace CreaCom\ProjectBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use FOS\UserBundle\Model\User as FOSUser;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\JoinColumn;
use Doctrine\ORM\Mapping\JoinTable;

/**
 * @ORM\Entity(repositoryClass="CreaCom\ProjectBundle\Entity\MembreRepository")
 * @ORM\Table(name="wbs_membres")
 */
class Membre extends FOSUser {
	/**
	 * @var integer
	 *
	 * @ORM\Column(name="id", type="integer")
	 * @ORM\Id
	 * @ORM\GeneratedValue(strategy="AUTO")
	 */
	protected $id;

	/**
	 * @var string
	 * @ORM\Column(type="string", nullable=true)
	 */
	protected $pseudo;

	/**
	 * @var string
	 * @ORM\Column(type="string", nullable=true)
	 */
	protected $nom;

	/**
	 * @var string
	 * @ORM\Column(type="string", nullable=true)
	 */
	protected $prenom;

	/**
	 * @var string
	 * @ORM\Column(type="string", nullable=true)
	 */
	protected $skype;

	/**
	 * @var string
	 * @ORM\Column(type="string", nullable=true)
	 */
	protected $facebook;

	/**
	 * @var string
	 * @ORM\Column(type="string", nullable=true)
	 */
	protected $twitter;

	/**
	 * @var \DateTime
	 * @ORM\Column(type="datetime")
	 */
	protected $dateInscription;

	/**
	 * @ORM\OneToOne(targetEntity="CreaCom\ProjectBundle\Entity\Image", cascade={"persist", "remove"})
	 * @ORM\JoinColumn(nullable=true)
	 */
	private $image;

	/**
	 * @var ArrayCollection
	 * @ORM\ManyToMany(targetEntity="CreaCom\ProjectBundle\Entity\Poste", fetch="EXTRA_LAZY")
	 * @ORM\JoinColumn(nullable=true)
	 * @ORM\OrderBy({"position" = "ASC"})
	 * @JoinTable(name="wbs_membres_postes",
	 *      joinColumns={@JoinColumn(name="membre_id", referencedColumnName="id")},
	 *      inverseJoinColumns={@JoinColumn(name="poste_id", referencedColumnName="id")}
	 * )
	 */
	private $poste;

	/**
	 * @var boolean $staff
	 * @ORM\Column(type="boolean")
	 */
	private $staff;

	/**
	 * @var boolean $remerciement
	 * @ORM\Column(type="boolean")
	 */
	private $remerciement = false;

	/**
	 * @var integer
	 * @ORM\Column(type="integer")
	 */
	private $order;


	public function __construct() {
		parent::__construct();
		$this->poste           = new ArrayCollection();
		$this->dateInscription = new \DateTime();
	}

	/**
	 * Get id
	 *
	 * @return integer
	 */
	public function getId() {
		return $this->id;
	}

	/**
	 * @return string
	 */
	public function getNom() {
		return $this->nom;
	}

	/**
	 * @return string
	 */
	public function getPrenom() {
		return $this->prenom;
	}

	/**
	 * @return string
	 */
	public function getSkype() {
		return $this->skype;
	}

	/**
	 * @return string
	 */
	public function getTwitter() {
		return $this->twitter;
	}

	/**
	 * @return string
	 */
	public function getFacebook() {
		return $this->facebook;
	}

	public function isStaff() {
		return $this->staff;
	}

	/**
	 * add poste
	 *
	 * @param Poste $poste
	 *
	 * @return Membre
	 */
	public function addPoste(Poste $poste) {
		$this->poste->add($poste);

		return $this;
	}

	/**
	 * remove poste
	 *
	 * @param Poste $poste
	 *
	 * @return Membre
	 */
	public function removePoste(Poste $poste) {
		$this->poste->removeElement($poste);

		return $this;
	}

	/**
	 * Get poste
	 *
	 * @return ArrayCollection
	 */
	public function getPostes() {
		return $this->poste;
	}

	/**
	 * @return mixed
	 */
	public function getImage() {
		return $this->image;
	}

	/**
	 * @param mixed $image
	 */
	public function setImage($image) {
		$this->image = $image;
	}


	/**
	 * @return string
	 */
	public function getPseudo() {
		return $this->pseudo;
	}

	/**
	 * @param string $pseudo
	 */
	public function setPseudo($pseudo) {
		$this->pseudo = $pseudo;
	}

	/**
	 * @return \DateTime
	 */
	public function getDateInscription() {
		return $this->dateInscription;
	}

	/**
	 * @param \DateTime $dateInscription
	 */
	public function setDateInscription($dateInscription) {
		$this->dateInscription = $dateInscription;
	}

	/**
	 * @return boolean
	 */
	public function isRemerciement() {
		return $this->remerciement;
	}

	/**
	 * @param boolean $remerciement
	 */
	public function setRemerciement($remerciement) {
		$this->remerciement = $remerciement;
	}

	/**
	 * @return int
	 */
	public function getOrder() {
		return $this->order;
	}

	/**
	 * @param int $order
	 */
	public function setOrder($order) {
		$this->order = $order;
	}
}

src/CreaCom/ProjectBundle/Entity/Project.php
<?php

namespace CreaCom\ProjectBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\JoinColumn;
use Doctrine\ORM\Mapping\JoinTable;

/**
 * Project
 *
 * @ORM\Table(name="wbs_project")
 * @ORM\Entity(repositoryClass="CreaCom\ProjectBundle\Entity\ProjectRepository")
 */
class Project {
	/**
	 * @var integer
	 *
	 * @ORM\Column(name="id", type="integer")
	 * @ORM\Id
	 * @ORM\GeneratedValue(strategy="AUTO")
	 */
	private $id;

	/**
	 * @var string
	 *
	 * @ORM\Column(name="name", type="string", length=255)
	 */
	private $name;

	/**
	 * @var string
	 *
	 * @ORM\Column(name="slug", type="string", length=255)
	 */
	private $slug;

	/**
	 * @var string
	 *
	 * @ORM\Column(name="video", type="string", length=255, nullable=true)
	 */
	private $video;

	/**
	 * @var string
	 *
	 * @ORM\Column(name="sortie", type="string", length=255, nullable=true)
	 */
	private $sortie;

	/**
	 * @ORM\ManyToOne(targetEntity="CreaCom\ProjectBundle\Entity\TypeProject", fetch="EXTRA_LAZY", inversedBy="projects")
	 */
	private $type;

	/**
	 * @var string
	 *
	 * @ORM\Column(name="description", type="text", nullable=true)
	 */
	private $description;

	/**
	 * @var string
	 *
	 * @ORM\Column(name="resume", type="text", nullable=true)
	 */
	private $resume;

	/**
	 * @var string
	 *
	 * @ORM\Column(name="banniere", type="string", length=255, nullable=true)
	 */
	private $banniere;
	/**
	 * @var ArrayCollection
	 * @ORM\ManyToMany(targetEntity="CreaCom\ProjectBundle\Entity\Membre", fetch="EXTRA_LAZY")
	 * @ORM\JoinColumn(nullable=true)
	 * @JoinTable(name="wbs_membres_projet",
	 *      joinColumns={@JoinColumn(name="project_id", referencedColumnName="id")},
	 *      inverseJoinColumns={@JoinColumn(name="membre_id", referencedColumnName="id")}
	 * )
	 */
	private $responsables;

	/**
	 * @ORM\OneToMany(targetEntity="CreaCom\ProjectBundle\Entity\Saison", fetch="EXTRA_LAZY", mappedBy="project")
	 * @ORM\OrderBy({"numero" = "ASC"})
	 */
	private $saisons;

	/**
	 * @ORM\OneToMany(targetEntity="CreaCom\ProjectBundle\Entity\Actualite", fetch="EXTRA_LAZY", mappedBy="projects")
	 * @ORM\OrderBy({"numero" = "DESC"})
	 */
	private $actualite;

	/**
	 * @ORM\OneToMany(targetEntity="CreaCom\ProjectBundle\Entity\Roles", fetch="EXTRA_LAZY", mappedBy="project")
	 */
	private $roles;

	/**
	 * @var boolean
	 *
	 * @ORM\Column(name="public", type="boolean")
	 */
	private $public = false;

	/**
	 * @var string
	 * @ORM\Column(name="background_url", type="string", nullable=true)
	 */
	private $background;

	/**
	 * @var string
	 * @ORM\Column(name="ext_lien", type="string", nullable=true)
	 */
	private $ext_lien;

	/**
	 * @var integer
	 * @ORM\Column(name="order", type="integer")
	 */
	private $order;

	/**
	 * @var boolean
	 *
	 * @ORM\Column(name="type_serie", type="boolean")
	 */
	private $serie;

	/**
	 * Project constructor.
	 */
	public function __construct() {
		$this->saisons      = new ArrayCollection();
		$this->actualite    = new ArrayCollection();
		$this->roles        = new ArrayCollection();
		$this->responsables = new ArrayCollection();
	}


	/**
	 * Get id
	 *
	 * @return integer
	 */
	public function getId() {
		return $this->id;
	}

	/**
	 * Get name
	 *
	 * @return string
	 */
	public function getName() {
		return $this->name;
	}

	/**
	 * Set name
	 *
	 * @param string $name
	 *
	 * @return Project
	 */
	public function setName($name) {
		$this->name = $name;

		return $this;
	}

	/**
	 * Get type
	 *
	 * @return string
	 */
	public function getType() {
		return $this->type;
	}

	/**
	 * Set type
	 *
	 * @param string $type
	 *
	 * @return Project
	 */
	public function setType($type) {
		$this->type = $type;

		return $this;
	}

	/**
	 * Get description
	 *
	 * @return string
	 */
	public function getDescription() {
		return $this->description;
	}

	/**
	 * Set description
	 *
	 * @param string $description
	 *
	 * @return Project
	 */
	public function setDescription($description) {
		$this->description = $description;

		return $this;
	}

	/**
	 * Get banniere
	 *
	 * @return string
	 */
	public function getBanniere() {
		return $this->banniere;
	}

	/**
	 * Set banniere
	 *
	 * @param string $banniere
	 *
	 * @return Project
	 */
	public function setBanniere($banniere) {
		$this->banniere = $banniere;

		return $this;
	}

	/**
	 * Get responsable
	 *
	 * @return string
	 */
	public function getResponsables() {
		return $this->responsables;
	}

	/**
	 * add responsable
	 *
	 * @param Membre $responsable
	 *
	 * @return Project
	 */
	public function addResponsable(Membre $responsable) {
		$this->responsables->add($responsable);

		return $this;
	}

	/**
	 * remove responsable
	 *
	 * @param Membre $responsable
	 *
	 * @return Project
	 */
	public function removeResponsable(Membre $responsable) {
		$this->responsables->removeElement($responsable);

		return $this;
	}

	/**
	 * Add saisons
	 *
	 * @param Saison $saison
	 *
	 * @return Project
	 */
	public function addSaison(Saison $saison) {
		$this->saisons->add($saison);

		return $this;
	}

	/**
	 * Remove saisons
	 *
	 * @param Saison $saison
	 *
	 * @return Project
	 */
	public function removeSaison(Saison $saison) {
		$this->saisons->removeElement($saison);

		return $this;
	}

	/**
	 * Get saisons
	 *
	 * @return ArrayCollection
	 */
	public function getSaisons() {
		return $this->saisons;
	}

	/**
	 * Add actualite
	 *
	 * @param Actualite $actualite
	 *
	 * @return Project
	 */
	public function addActualite(Actualite $actualite) {
		$this->actualite->add($actualite);

		return $this;
	}

	/**
	 * Remove actualite
	 *
	 * @param Actualite $actualite
	 *
	 * @return Project
	 */
	public function removeActualite(Actualite $actualite) {
		$this->actualite->removeElement($actualite);

		return $this;
	}

	/**
	 * Get actualite
	 *
	 * @return ArrayCollection
	 */
	public function getActualites() {
		return $this->actualite;
	}

	/**
	 * @return boolean
	 */
	public function isPublic() {
		return $this->public;
	}

	/**
	 * @param boolean $public
	 */
	public function setPublic($public) {
		$this->public = $public;
	}

	/**
	 * Add role
	 *
	 * @param Roles $role
	 *
	 * @return Project
	 */
	public function addRole(Roles $role) {
		$this->roles->add($role);

		return $this;
	}

	/**
	 * Remove role
	 *
	 * @param Roles $role
	 *
	 * @return Project
	 */
	public function removeRole(Roles $role) {
		$this->roles->removeElement($role);

		return $this;
	}

	/**
	 * Get Roles
	 *
	 * @return ArrayCollection
	 */
	public function getRoles() {
		return $this->roles;
	}

	/**
	 * @return string
	 */
	public function getBackground() {
		return $this->background;
	}

	/**
	 * @param string $bgUrl
	 *
	 * @return $this
	 */
	public function setBackground($bgUrl) {
		$this->background = $bgUrl;

		return $this;
	}

	/**
	 * @return boolean
	 */
	public function isSerie() {
		return $this->serie;
	}

	/**
	 * @return mixed
	 */
	public function getSlug() {
		return $this->slug;
	}

	/**
	 * @param mixed $slug
	 */
	public function setSlug($slug) {
		$this->slug = $slug;
	}

	/**
	 * @return mixed
	 */
	public function getVideo() {
		return $this->video;
	}

	/**
	 * @param mixed $video
	 */
	public function setVideo($video) {
		$this->video = $video;
	}

	/**
	 * @return mixed
	 */
	public function getSortie() {
		return $this->sortie;
	}

	/**
	 * @param mixed $sortie
	 */
	public function setSortie($sortie) {
		$this->sortie = $sortie;
	}

	/**
	 * @return string
	 */
	public function getExtLien() {
		return $this->ext_lien;
	}

	/**
	 * @param string $ext_lien
	 */
	public function setExtLien($ext_lien) {
		$this->ext_lien = $ext_lien;
	}

	/**
	 * @return int
	 */
	public function getOrder() {
		return $this->order;
	}

	/**
	 * @param int $order
	 */
	public function setOrder($order) {
		$this->order = $order;
	}

	/**
	 * @return string
	 */
	public function getResume() {
		return $this->resume;
	}

	/**
	 * @param string $resume
	 */
	public function setResume($resume) {
		$this->resume = $resume;
	}
}

src/CreaCom/ProjectBundle/Resources/views/SiteCreaCom/presentation.html.twig
{% extends "@CreaComProject/layout.html.twig" %}
{% block pageTitle %}Présentation{% endblock %}
{% block extrasStyle %}
	{% stylesheets
	'bundles/creacomproject/css/pagePresentation.css' filter='cssrewrite' %}
	<link href="{{ asset_url }}" rel="stylesheet" type="text/css" xmlns="http://www.w3.org/1999/html" />
	{% endstylesheets %}
{% endblock %}
{% block container %}
	<div class="container">
		<div class="col-xs-14 bloc-ext">
			<div class="bloc-int">
				<div class="bloc-header"
				     style="background-image:url('{{ asset('bundles/creacomproject/images/presentation/background-presentation.jpg') }}');background-size: cover;background-position: 25% 28%;">
					{#<div class="col-lg-2"><img src="{{ asset('bundles/creacomproject/images/minilogo.png') }}"#}
					{#alt="logo"/></div>#}
					<h1 class="col-lg-12">PRÉSENTATION</h1>
				</div>
				<div class="bloc-presentation-generale">
					<p class="text-justify">
						Creative Community est un studio de développement de projets artistiques et créatifs spécialisé
						dans le contenu audiovisuel sur internet fondé début 2013 par Benjamin Maublanc et Lucien
						Gillonnier.<br />
						Suite à la création de StarCube : Galaxy et à la sortie du premier épisode le 9 février 2013, le
						studio Creative Community est fondé pour supporter le développement de cette série, mais aussi
						à terme d’autres productions.<br /><br />

						Le 11 avril 2013 le studio prend la forme d’une association, jouissant alors d’une existence
						morale, lui permettant de fonctionner de façon structurée toujours dans l’objectif de développer
						des productions innovantes.<br />
						Le studio Creative Community a toujours cherché à repousser les limites pour proposer aux
						spectateurs un contenu intéressant, pour les faire voyager dans d’autres mondes, leur faire
						découvrir de grands univers tous plus grandioses et profonds les uns que les autres.<br /><br />

						Au fil de son évolution le studio a su rassembler de nombreux talents. Originellement composée
						d’une quinzaine de personnes, l’association compte en novembre 2013, après huit mois
						d’existence, plus de trente membres aux compétences et qualifications diverses.<br />
						Aujourd’hui notre association progresse rapidement et est soutenue par de nombreux acteurs de la
						communauté. Nous continuons de travailler pour produire un divertissement intéressant et
						régulier accessible par tous et ce gratuitement.
					</p>
				</div>
				<div class="bloc-presentation-membres text-center">
					{% if leStaff is defined and leStaff is not null and leStaff|length > 0 %}
						<h3>Membres <span style="font-size: 16px;">({{ leStaff|length }})</span></h3>
						{% for membre in leStaff %}
							<div class="user text-center">
								{% if membre.image is not null %}
									<img id="image{{ membre.id }}" style="width: 128px;height:128px;"
									     src="{{ asset('bundles/creacomproject/images/membres/'~membre.image.name) }}" />
								{% else %}
									<img id="image{{ membre.id }}" style="width: 128px;height:128px;"
									     src="{{ asset('bundles/creacomproject/images/membres/none.png') }}" />
								{% endif %}
								<p id="texte{{ membre.id }}"
								   class="nom text-center">{% if membre.nom is not null and membre.prenom is not null %}{{ membre.prenom }} {{ membre.nom }}{% else %}{{ membre.pseudo }}{% endif %}</p>
								<h2 class="role text-center">{% for poste in membre.postes %}{{ poste.nom }}{% if loop.last == false %} - {% endif %}{% endfor %}</h2>
							</div>
						{% endfor %}
					{% else %}
						<h3> Aucun membre pour le moment</h3>
					{% endif %}
					{% if lesRemerciements is defined and lesRemerciements is not null and lesRemerciements|length > 0 %}
						<h3 class="margin-bottom-20">Remerciements <span style="font-size: 16px;">({{ lesRemerciements|length }})</span></h3>
						<div class="row">
							{% set i = 0 %}
							{% for remerciement in lesRemerciements %}
								{% if i== 0 %}
									<div class="row">
								{% endif %}
								<div class="col-sm-7" style="text-align: center">
									<p style="margin-bottom: 0;    font-size: 14px;font-family: 'Dosis', sans-serif;">{% if remerciement.nom is not null and remerciement.prenom is not null %}{{ remerciement.prenom }} {{ remerciement.nom }}{% else %}{{ remerciement.pseudo }}{% endif %}&ensp;{% if remerciement.postes is not null %} ({% endif %}{% for poste in remerciement.postes %}{{ poste.nom }}{% if loop.last == false %}, {% endif %}{% endfor %}{% if remerciement.postes is not null %}){% endif %}</p>
								</div>
								{% set i = i+1 %}
								{% if i == 2 or loop.last %}
									</div>
									{% set i = 0 %}
								{% endif %}
							{% endfor %}
						</div>
					{% endif %}
				</div>
			</div>
		</div>
	</div>
{% endblock %}

src/CreaCom/ProjectBundle/Resources/views/SiteCreaCom/projet.html.twig
{% extends "@CreaComProject/layout.html.twig" %}
{% block pageTitle %}Projet{% endblock %}
{% block extrasStyle %}
	{% stylesheets
	'bundles/creacomproject/css/pageProjet.css' filter='cssrewrite' %}
	<link href="{{ asset_url }}" rel="stylesheet" type="text/css" xmlns="http://www.w3.org/1999/html" />
	{% endstylesheets %}
{% endblock %}
{% block styleBody %}style="background: url('{{ asset('bundles/creacomproject/images/projets/'~ project.slug ~'/fond.jpg') }}') fixed no-repeat;background-size:cover;"{% endblock %}
{% block container %}
	<div class="col-xs-14 bloc-ext">
		<div class="bloc-int col-xs-14">
			<div class="bloc-header"
			     style="background-image:url('{{ asset('bundles/creacomproject/images/projets/'~project.slug~'/background.jpg') }}');"></div>
			<div class="bloc-principal col-sm-10">
				<div class="bloc-video col-sm-14">
					<iframe src="https://www.youtube.com/embed/{{ project.video }}" frameborder="0"
					        allowfullscreen></iframe>
				</div>
				<div class="bloc-actu col-sm-14">
					<!-- Nav tabs -->
					<nav id="tabs" class="onglets col-sm-14">

						{% set tabindex = 1 %}

						{% if project.actualites|length > 0 %}
							<div class="tab" tabindex="0"><a href="#actu" data-title="Actualités" aria-controls="actu" role="tab" data-toggle="tab">
								Actualités
							</a></div>
						{% endif %}
						{% for saison in project.saisons %}
							{% if loop.first and project.actualites|length < 1 %}
								<div class="tab" tabindex="{{ tabindex }}"><a href="#saison{{ saison.id }}" data-title="{{ saison.name|capitalize }}"
								   aria-controls="saison{{ saison.id }}" role="tab" data-toggle="tab">
									{{ saison.name|capitalize }}
								</a></div>
							{% else %}
								{% set tabindex = tabindex + 1 %}
								<div class="tab" tabindex="{{ tabindex }}"><a href="#saison{{ saison.id }}" aria-controls="saison{{ saison.id }}" role="tab"
								   data-toggle="tab" data-title="{{ saison.name|capitalize }}">
									{{ saison.name|capitalize }}
								</a></div>
							{% endif %}
						{% endfor %}

					</nav>
					<!-- Tab panes -->
					<div class="tab-content">
						{% if project.actualites|length > 0 %}
							<div role="tabpanel" class="tab-pane active" id="actu">
								{% for actualite in project.actualites %}
									<div class="actualité col-sm-14">
										<div id="image{{ actualite.id }}" class="image col-sm-5"><img src="{{ asset('bundles/creacomproject/images/projets/'~project.slug~'/'~actualite.image) }}" /></div>
										<div id="contenu{{ actualite.id }}" class="col-sm-9">
											<div class="contenu col-sm-14">
												<h2>{{ actualite.titre }}</h2>
											</div>
											<div class="contenu col-sm-14">
												<p class="comment more">{{ actualite.description|raw }}</p>
											</div>
										</div>
									</div>
									{#<div class="nav-articles text-center col-sm-14"><b>1</b> | 2 >></div>#}
								{% endfor %}
							</div>
						{% endif %}
						{% for saison in project.saisons %}
							<div role="tabpanel" class="tab-pane {% if loop.first and project.actualites|length < 1 %}active{% endif %}" id="saison{{ saison.id }}">
								{% if saison.episodes is not null  and saison.episodes|length > 0 %}
									{% for episode in saison.episodes %}
										<a style="color: black"
										   href="https://www.youtube.com/watch?v={{ episode.youtube }}" target="_blank">
											<div class="actualité col-sm-14">
												<div id="imageS{{ saison.id }}" class="image col-sm-5"><img src="{{ asset('bundles/creacomproject/images/projets/'~project.slug~'/'~episode.miniature) }}" /></div>
												<div id="contenuS{{ saison.id }}E{{ episode.id }}" class="col-sm-9">
													<div class="contenu col-sm-14">
														<h2>{{ episode.name }}</h2>
													</div>
													<div class="contenu col-sm-14">
														<p class="comment more">{{ episode.description|raw }}</p>
													</div>
												</div>
											</div>
										</a>
										{#<div class="nav-articles text-center col-sm-14"><b>1</b> | 2 >></div>#}
									{% endfor %}
								{% else %}
									<h3>Pas d'épisode pour cette saison</h3>
								{% endif %}
							</div>
						{% endfor %}
					</div>
				</div>
			</div>
			<div class="col-sm-4 bloc-vide"></div>
			<div class="bloc-info col-sm-4">
				<div class="presentation">
					<h2>PRESENTATION</h2>
					<p class="text-justify">
						{{ project.description|raw }}
					</p>
				</div>
				{% if project.responsables is not null %}
					<div class="createurs">
						<h2>LES CREATEURS</h2>
						{% for createur in project.responsables %}
							<div class="membre text-center">
								<img height="128" width="128" src="{{ asset('bundles/creacomproject/images/membres/'~createur.image.name) }}"
								     alt="avatar" />
								<p style="color: #000;" id="texte{{ createur.id }}"
								   class="nom text-center">{{ createur.prenom }} {{ createur.nom }}</p>
							</div>
						{% endfor %}
					</div>
				{% endif %}
			</div>
			<div class="col-sm-4 bloc-vide"></div>
		</div>
	</div>
{% endblock %}
{% block extraScript %}
	<script src="{{ asset('bundles/creacomproject/js/Shorten.js') }}"></script>
	<script type="text/javascript">
		var indexSelected = 0;
		function applyShadow() {

			$('#tabs').find('.tab').each(function() {
				if($(this).attr('tabindex') == indexSelected) {
					$(this).css('text-shadow', '1px 1px 20px grey');
					$(this).css('font-weight', 'bold');
				} else {
					$(this).css('text-shadow', 'none');
					$(this).css('font-weight', 'normal');
				}
			});

		}
		$(document).ready(function () {
			$(".comment").shorten();

			applyShadow();

			$('#tabs').find('.tab').find('a').click(function (e) {
				indexSelected = $(this).parent().attr('tabindex');
				applyShadow();
			});
		});
	</script>
{% endblock %}

src/CreaCom/ProjectBundle/Resources/views/SiteCreaCom/projets.html.twig
{% extends "@CreaComProject/layout.html.twig" %}
{% block pageTitle %}Projets{% endblock %}
{% block extrasStyle %}
	{% stylesheets
	'bundles/creacomproject/css/pageListProjets.css'
	'bundles/creacomproject/css/pageIndex.css'
	'bundles/creacomproject/css/pageProjets.css'
	filter='cssrewrite' %}
	<link href="{{ asset_url }}" rel="stylesheet" type="text/css" xmlns="http://www.w3.org/1999/html" />
	{% endstylesheets %}
{% endblock %}
{% block container %}
	{% for projet in projects %}
		<div class="col-xs-14 bloc-ext">
			<div class="bloc-presentation-postes">
				<div class="poste-image col-sm-7"
				     style="background: url(data:image/jpeg;base64,{{ banners[projet.id] }}) no-repeat; background-size: cover; background-position: right bottom;">
				</div>
				<div class="poste-resume col-sm-6">
					<h2 class="text-center">
						{{ projet.name|upper }}
					</h2>
					<p class="description-projet">
						{{ projet.description|raw }}
					</p>
					{% if projet.video is not null and projet.serie == false and projet.extLien is not null %}
						<div class="col-md-14"><a style="padding-left: 6px;text-align: center;" target="_blank"
						                          href="{{ projet.extLien }}"
						                          class="big-more-button">EN SAVOIR PLUS</a></div>
					{% elseif projet.video is not null %}
						<div class="col-md-14"><a style="padding-left: 6px;text-align: center;margin-top: 20px;"
						                          href="{{ path('creacom_sitecreacom_projet', {slug: projet.slug}) }}"
						                          class="big-more-button">EN SAVOIR PLUS</a></div>
					{% else %}
						<div class="col-md-14 soon"><a style="padding-left: 6px;text-align: center;margin-top: 20px;"
						                          href="#"
						                          class="big-more-button">PROCHAINEMENT</a></div>
					{% endif %}
				</div>
			</div>
		</div>
	{% endfor %}
{% endblock %}